# -*- coding: utf-8 -*-
"""US-4ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zOkvCrAm-XfIYsi4tYvK9FLnHXCC8UY3
"""

from google.colab import files
uploaded = files.upload()

top_neighbourhoods = (
    neighbourhood_ranking.rank_neighbourhoods(
        neighbourhood_ranking.cleaned_df
    )
)

top_neighbourhoods



import pandas as pd


def rank_neighbourhoods(
    cleaned_df: pd.DataFrame,
    neighbourhood_column: str = "NEIGHBOURHOOD_158",
    top_n: int = 10
) -> pd.DataFrame:
    """
    Rank neighbourhoods based on total crime count.

    Parameters:
        cleaned_df (pd.DataFrame): Cleaned Toronto crime dataset.
        neighbourhood_column (str): Column containing neighbourhood names.
        top_n (int): Number of top neighbourhoods to return.

    Returns:
        pd.DataFrame: Ranked neighbourhoods with crime counts.
    """

    if neighbourhood_column not in cleaned_df.columns:
        raise ValueError(f"Column not found: {neighbourhood_column}")

    ranking_df = (
        cleaned_df[neighbourhood_column]
        .dropna()
        .value_counts()
        .reset_index()
    )

    ranking_df.columns = ["neighbourhood", "crime_count"]

    ranking_df["rank"] = ranking_df["crime_count"].rank(
        method="dense",
        ascending=False
    ).astype(int)

    ranking_df = ranking_df.sort_values(
        by=["crime_count", "neighbourhood"],
        ascending=[False, True]
    )

    return ranking_df.head(top_n)


def filter_neighbourhood_ranking(
    cleaned_df: pd.DataFrame,
    selected_neighbourhood: str = None,
    neighbourhood_column: str = "NEIGHBOURHOOD_158"
) -> pd.DataFrame:
    """
    Filter dataset by selected neighbourhood.

    Parameters:
        cleaned_df (pd.DataFrame): Cleaned Toronto crime dataset.
        selected_neighbourhood (str): Neighbourhood selected by user.
        neighbourhood_column (str): Column containing neighbourhood names.

    Returns:
        pd.DataFrame: Filtered dataset.
    """

    if neighbourhood_column not in cleaned_df.columns:
        raise ValueError(f"Column not found: {neighbourhood_column}")

    if selected_neighbourhood is None or selected_neighbourhood == "All":
        return cleaned_df

    return cleaned_df[
        cleaned_df[neighbourhood_column] == selected_neighbourhood
    ]


cleaned_df = pd.read_csv("cleaned_toronto_crime.csv")

top_neighbourhoods = rank_neighbourhoods(
    cleaned_df,
    top_n=10
)

print("Top High-Risk Neighbourhoods")
print("-" * 35)
print(top_neighbourhoods)

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))

plt.barh(
    top_neighbourhoods["neighbourhood"],
    top_neighbourhoods["crime_count"]
)

plt.xlabel("Crime Count")
plt.ylabel("Neighbourhood")

plt.title("Top High-Risk Neighbourhoods")

plt.gca().invert_yaxis()

plt.show()

!pip install folium

import pandas as pd
import folium
from folium.plugins import MarkerCluster

df = pd.read_csv("cleaned_toronto_crime.csv")

df.head()

df[["NEIGHBOURHOOD_158", "LAT_WGS84", "LONG_WGS84"]].head()

import pandas as pd
import matplotlib.pyplot as plt

# Load cleaned data
df = pd.read_csv("cleaned_toronto_crime.csv")

# Get top 10 neighbourhoods by crime count
top_10_neighbourhoods = (
    df["NEIGHBOURHOOD_158"]
    .value_counts()
    .head(10)
    .index
)

# Filter data for top 10 neighbourhoods only
map_df = df[
    df["NEIGHBOURHOOD_158"].isin(top_10_neighbourhoods)
].copy()

# Create summary table for labels
top_10_summary = (
    map_df.groupby("NEIGHBOURHOOD_158")
    .agg(
        crime_count=("NEIGHBOURHOOD_158", "count"),
        avg_lat=("LAT_WGS84", "mean"),
        avg_long=("LONG_WGS84", "mean")
    )
    .reset_index()
    .sort_values("crime_count", ascending=False)
)

top_10_summary

plt.figure(figsize=(10, 8))

plt.scatter(
    map_df["LONG_WGS84"],
    map_df["LAT_WGS84"],
    alpha=0.15,
    s=8
)

# Add neighbourhood labels at average location
for _, row in top_10_summary.iterrows():
    plt.text(
        row["avg_long"],
        row["avg_lat"],
        row["NEIGHBOURHOOD_158"],
        fontsize=9,
        ha="center"
    )

plt.xlabel("Longitude")
plt.ylabel("Latitude")
plt.title("Top 10 High-Risk Neighbourhoods in Toronto")

plt.grid(True)

plt.show()



# Get top 10 high-risk neighbourhoods
top_neighbourhoods = (
    df["NEIGHBOURHOOD_158"]
    .value_counts()
    .head(10)
    .index
)

# Filter dataset to top neighbourhoods only
map_df = df[df["NEIGHBOURHOOD_158"].isin(top_neighbourhoods)]

# Optional: sample data so the map does not become too slow
map_df = map_df.sample(
    n=min(3000, len(map_df)),
    random_state=42
)

# Create Toronto map
toronto_map = folium.Map(
    location=[43.6532, -79.3832],
    zoom_start=11
)

marker_cluster = MarkerCluster().add_to(toronto_map)

for _, row in map_df.iterrows():
    folium.Marker(
        location=[row["LAT_WGS84"], row["LONG_WGS84"]],
        popup=f"""
        Neighbourhood: {row["NEIGHBOURHOOD_158"]}<br>
        Offence: {row["OFFENCE"]}
        """
    ).add_to(marker_cluster)

toronto_map

toronto_map.save("toronto_neighbourhood_crime_map.html")