import pandas as pd


def generate_crime_overview(cleaned_df: pd.DataFrame) -> dict:
    """
    Generate a high-level Toronto crime risk overview.

    This function is designed to run after US-02 data cleaning.
    Input should be the cleaned dataset generated by US-02.
    """

    data = cleaned_df.copy()

    total_crimes = len(data)

    most_common_offence = (
        data["OFFENCE"].mode().iloc[0]
        if "OFFENCE" in data.columns and not data["OFFENCE"].dropna().empty
        else None
    )

    highest_crime_neighbourhood = (
        data["NEIGHBOURHOOD_158"].value_counts().idxmax()
        if "NEIGHBOURHOOD_158" in data.columns
        and not data["NEIGHBOURHOOD_158"].dropna().empty
        else None
    )

    total_neighbourhoods = (
        data["NEIGHBOURHOOD_158"].nunique()
        if "NEIGHBOURHOOD_158" in data.columns
        else None
    )

    return {
        "total_crimes": total_crimes,
        "most_common_offence": most_common_offence,
        "highest_crime_neighbourhood": highest_crime_neighbourhood,
        "total_neighbourhoods": total_neighbourhoods,
    }
