# -*- coding: utf-8 -*-
"""crime_overview.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_MEk_Jx-Zmu6bSqSFwE74dbORb45mEj9
"""

"""
US-03: Generate Toronto Crime Risk Overview

Task 2: Build Crime Overview Function

Acceptance Criteria:
✓ Function returns all KPIs
✓ No errors
✓ Output reusable for dashboard
"""

import pandas as pd


def generate_crime_overview(cleaned_df: pd.DataFrame) -> dict:
    """
    Generate reusable crime overview KPIs from the cleaned dataset.
    """

    total_crimes = len(cleaned_df)

    most_common_offence = (
        cleaned_df["OFFENCE"].dropna().mode().iloc[0]
        if not cleaned_df["OFFENCE"].dropna().empty
        else "Not Available"
    )

    most_common_offence_count = (
        int(cleaned_df["OFFENCE"].value_counts().max())
        if not cleaned_df["OFFENCE"].dropna().empty
        else 0
    )

    highest_crime_neighbourhood = (
        cleaned_df["NEIGHBOURHOOD_158"].dropna().value_counts().idxmax()
        if not cleaned_df["NEIGHBOURHOOD_158"].dropna().empty
        else "Not Available"
    )

    highest_crime_neighbourhood_count = (
        int(cleaned_df["NEIGHBOURHOOD_158"].value_counts().max())
        if not cleaned_df["NEIGHBOURHOOD_158"].dropna().empty
        else 0
    )

    total_neighbourhoods = (
        cleaned_df["NEIGHBOURHOOD_158"].nunique()
    )

    total_offence_types = (
        cleaned_df["OFFENCE"].nunique()
    )

    return {
        "total_crimes": total_crimes,
        "most_common_offence": most_common_offence,
        "most_common_offence_count": most_common_offence_count,
        "highest_crime_neighbourhood": highest_crime_neighbourhood,
        "highest_crime_neighbourhood_count": highest_crime_neighbourhood_count,
        "total_neighbourhoods": total_neighbourhoods,
        "total_offence_types": total_offence_types,
    }


if __name__ == "__main__":

    # Load cleaned dataset from US-02
    cleaned_df = pd.read_csv("cleaned_toronto_crime.csv")

    # Generate overview KPIs
    crime_overview = generate_crime_overview(cleaned_df)

    print("Toronto Crime Risk Overview")
    print("-" * 35)

    for key, value in crime_overview.items():
        print(f"{key}: {value}")