# -*- coding: utf-8 -*-
"""Copy of data_cleaning.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uGQwgauJnpaSFXY2h1xgMNNZpwGQRYUp
"""

"""
US-02: Validate and Clean Crime Data

User Story:
As a crime analyst, I want invalid or incomplete records handled
so that insights are reliable.

Acceptance Criteria:
- Missing values identified
- "NSA" entries handled
- Invalid coordinates removed
- Cleaning summary shown
"""

import pandas as pd
import gdown

# -----------------------------
# Load Dataset
# -----------------------------

FILE_ID = "1fGiMMzoqixBSj16cDidPlkNkpz6BdovU"
OUTPUT_PATH = "Toronto_Crime_Indicators.csv"

gdown.download(
    f"https://drive.google.com/uc?id={FILE_ID}",
    OUTPUT_PATH,
    quiet=False
)

crime_df = pd.read_csv(OUTPUT_PATH)

# -----------------------------
# Missing Values
# -----------------------------

missing_values = crime_df.isnull().sum()
missing_values = missing_values[missing_values > 0]

# -----------------------------
# Handle NSA Entries
# -----------------------------

cleaned_df = crime_df.copy()

for column in cleaned_df.columns:
    if cleaned_df[column].dtype == "object":
        cleaned_df[column] = cleaned_df[column].replace(
            "NSA",
            "Unknown"
        )

# -----------------------------
# Remove Invalid Coordinates
# -----------------------------

cleaned_df = cleaned_df[
    (cleaned_df["LAT_WGS84"].notnull()) &
    (cleaned_df["LONG_WGS84"].notnull()) &
    (cleaned_df["LAT_WGS84"] != 0) &
    (cleaned_df["LONG_WGS84"] != 0)
]

# -----------------------------
# Cleaning Summary
# -----------------------------

original_rows = len(crime_df)
final_rows = len(cleaned_df)

print("Cleaning Summary")
print("-" * 30)

print(f"Original Rows: {original_rows}")
print(f"Final Rows: {final_rows}")
print(f"Rows Removed: {original_rows - final_rows}")

print("\nMissing Values Found:")

if len(missing_values) > 0:
    print(missing_values)
else:
    print("No missing values found.")

print("\nCleaned Dataset Preview:")
print(cleaned_df.head())