# -*- coding: utf-8 -*-
"""data_loader

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v_x6Og1Byb8efuZNXTCGf8GgX4dfbMzk
"""

!pip install gdown

import gdown
import pandas as pd
from pathlib import Path

FILE_ID = "1fGiMMzoqixBSj16cDidPlkNkpz6BdovU"
OUTPUT_PATH = "Toronto_Crime_Indicators.csv"


def load_dataset():

    try:
        # Download dataset if it doesn't exist
        if not Path(OUTPUT_PATH).exists():

            print("Downloading dataset from Google Drive...")

            gdown.download(
                f"https://drive.google.com/uc?id={FILE_ID}",
                OUTPUT_PATH,
                quiet=False
            )

        df = pd.read_csv(OUTPUT_PATH)

        if df.empty:
            raise ValueError(
                "Dataset loaded successfully but contains no records."
            )

        print("Dataset loaded successfully.")

        return df

    except FileNotFoundError:
        print(f"Dataset file not found: {OUTPUT_PATH}")
        return None

    except Exception as error:
        print(f"Error loading dataset: {error}")
        return None


def preview_dataset(df):
    print("\nDataset Preview:")
    print(df.head())


def get_dataset_summary(df):

    return {
        "total_rows": df.shape[0],
        "total_columns": df.shape[1],
        "column_names": list(df.columns)
    }


if __name__ == "__main__":

    crime_df = load_dataset()

    if crime_df is not None:

        preview_dataset(crime_df)

        print("\nDataset Summary:")
        print(get_dataset_summary(crime_df))
