# -*- coding: utf-8 -*-
"""neighbourhood_ranking.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15bLqNIgwOrSQIyqFRbpUf7-UdP1izOD7
"""

"""
US-04: Identify High-Risk Neighbourhoods

Task 2: Build Neighbourhood Ranking Function

User Story:
As a resident, I want neighbourhood crime rankings
so that I can identify higher-risk areas.

Acceptance Criteria:
- Top neighbourhoods displayed
- Ranking visualization included
- Filter available
"""

import pandas as pd


def rank_neighbourhoods(
    cleaned_df: pd.DataFrame,
    neighbourhood_column: str = "NEIGHBOURHOOD_158",
    top_n: int = 10
) -> pd.DataFrame:
    """
    Rank neighbourhoods based on total crime count.

    Parameters:
        cleaned_df (pd.DataFrame): Cleaned Toronto crime dataset.
        neighbourhood_column (str): Column containing neighbourhood names.
        top_n (int): Number of top neighbourhoods to return.

    Returns:
        pd.DataFrame: Ranked neighbourhoods with crime counts.
    """

    if neighbourhood_column not in cleaned_df.columns:
        raise ValueError(f"Column not found: {neighbourhood_column}")

    ranking_df = (
        cleaned_df[neighbourhood_column]
        .dropna()
        .value_counts()
        .reset_index()
    )

    ranking_df.columns = ["neighbourhood", "crime_count"]

    ranking_df["rank"] = ranking_df["crime_count"].rank(
        method="dense",
        ascending=False
    ).astype(int)

    ranking_df = ranking_df.sort_values(
        by=["crime_count", "neighbourhood"],
        ascending=[False, True]
    )

    return ranking_df.head(top_n)


def filter_neighbourhood_ranking(
    cleaned_df: pd.DataFrame,
    selected_neighbourhood: str = None,
    neighbourhood_column: str = "NEIGHBOURHOOD_158"
) -> pd.DataFrame:
    """
    Filter dataset by selected neighbourhood.

    Parameters:
        cleaned_df (pd.DataFrame): Cleaned Toronto crime dataset.
        selected_neighbourhood (str): Neighbourhood selected by user.
        neighbourhood_column (str): Column containing neighbourhood names.

    Returns:
        pd.DataFrame: Filtered dataset.
    """

    if neighbourhood_column not in cleaned_df.columns:
        raise ValueError(f"Column not found: {neighbourhood_column}")

    if selected_neighbourhood is None or selected_neighbourhood == "All":
        return cleaned_df

    return cleaned_df[
        cleaned_df[neighbourhood_column] == selected_neighbourhood
    ]


cleaned_df = pd.read_csv("cleaned_toronto_crime.csv")

top_neighbourhoods = rank_neighbourhoods(
    cleaned_df,
    top_n=10
)

print("Top High-Risk Neighbourhoods")
print("-" * 35)
print(top_neighbourhoods)